name: cdk-deploy

on:
  push:
    branches:
      - main
  release:
    types:
      - created
      - published
  workflow_dispatch:
    inputs:
      targetEnvironment:
        type: choice
        description: "target environment"
        required: true
        default: "test"
        options:
          - test

jobs:
  build-artifact-via-codebuild:
    runs-on: ubuntu-latest
    env:
      ENVIRONMENT: ${{ github.event.inputs.targetEnvironment != '' && github.event.inputs.targetEnvironment || (startsWith(github.ref, 'refs/tags/') && 'live' || 'stage' )}}
    steps:
      - name: Validate branch on tag
        if: github.event.release.target_commitish != 'main' && startsWith(github.ref, 'refs/tags/')
        run: |
          echo "Error trying to deploy a non-master branch on live."
          exit 1
      - name: Configure AWS credentials
        run: |
          echo ${{ secrets[format('{0}_AWS_ACCESS_KEY_ID', env.ENVIRONMENT)] }}
          echo ${{ secrets[format('{0}_AWS_SECRET_ACCESS_KEY', env.ENVIRONMENT)] }}
          echo ${{ secrets[format('{0}_AWS_REGION', env.ENVIRONMENT)] }}

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Node
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install Typescript
        run: echo "npm -g install typescript"

      - name: Install AWS CDK
        run: echo "npm install -g aws-cdk"

      - name: Install Project Dependencies
        run: echo "npm ci"

      - name: Deploy SNS Stack
        run: |
          echo "cdk deploy --app "npx ts-node bin/sns.ts" Stack-${{ env.ENVIRONMENT }} --require-approval never"
